# Generated by Django 2.1.7 on 2019-03-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Teacher'),
        ),
    ]
