# Generated by Django 2.1.7 on 2019-03-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_id',
            new_name='teacher_id',
        ),
    ]
